apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-pod
    image: nginx
    # 创建一个SUCCESS文件后退出
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "touch /mnt/SUCCESS && exit 0 || exit 1"
    volumeMounts:
      - name: nfs-pvc
        mountPath: "/mnt"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  restartPolicy: Never
  volumes:
    - name: nfs-pvc
    # 与pvc.yaml中定义的名称一致
      persistentVolumeClaim:
        claimName: test-claim



        