apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-claim
  # 需要与nfs-StorageClass.yaml中的metadata.name相同
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  resources:
    requests:
      storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
