apiVersion: v1
kind: Pod
metadata:
  name: dependent-envars-demo
  labels:
    name: dependent-envars-demo
spec:
  containers:
  - name: dependent-envars-demo
    command:
      - "sh"
      - "-c"
    args:
      - "printf UUNCHANGED_REFERENCE=$UUNCHANGED_REFERENCE'\n'; printf SERVICE_ADDRESS=$SERVICE_ADDRESS'\n'; printf ESCAPED_REFERENCE=$ESCAPED_REFERENCE'\n';"
    env:
      - name: SERVICE_PORT
        value: "80"
      - name: SERVICE_IP
        value: "172.17.0.1"
        # 引用了其他环境变量, 但是此时这个变量还没有定义，故会被当成普通字符串处理
      - name: UUNCHANGED_REFERENCE
        value: "$(PROTOCOL)://$(SERVICE_IP):$(SERVICE_PORT)"
      - name: PROTOCOL
        value: "https"
        # 可以正常显示
      - name: SERVICE_ADDRESS
        value: "$(PROTOCOL)://$(SERVICE_IP):$(SERVICE_PORT)"
        # $$(PROTOCOL): $(PROTOCOL)会被转义，无论它引用的变量是否存在，都不会被解析，而是当成一个普通字符串处理
      - name: ESCAPED_REFERENCE
        value: "$$(PROTOCOL)://$(SERVICE_IP):$(SERVICE_PORT)"
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
