apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
  labels:
    name: security-context-demo
spec:
  securityContext:
    # 容器内的进程都是用ID=1000的用户运行
    runAsUser: 1000
    # 容器内的进程的主要组ID
    runAsGroup: 3000
    # 容器内卷的附加组，在这个卷内创建的目录和文件都属于这个组
    fsGroup: 2000
  volumes:
  # 设置一个名为sec-ctx-vol的卷
    - name: sec-ctx-vol
    # 挂在一个宿主机的随机空目录，用于存放Pod的内容
      emptyDir: {}
  containers:
  - name: security-context-demo
    image: busybox
    command: ["sh", "-c", "sleep 1h"]
    volumeMounts:
      - name: sec-ctx-vol
      # 存储到挂载卷的/data/demo目录下
        mountPath: /data/demo
    securityContext:
    # 是否让权限越出
      allowPrivilegeEscalation: false
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
