apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
  labels:
    name: hostpath-pod
spec:
  containers:
  - name: hostpath-pod
    image: nginx
    volumeMounts:
    # 挂载的卷在容器中的路径
    - mountPath: /test-nginx
      name: my-host-path
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
      # 定义容器挂载的卷
  volumes:
    - name: my-host-path
      hostPath:
      # 宿主机中的目录
        path: /tmp/nginx
        type: DirectoryOrCreate
