apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
  labels:
    name: nfs-pod
spec:
  containers:
  - name: nfs-pod
    image: nginx
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: nfs-svc
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  volumes:
    - name: nfs-svc
      nfs:
      # 服务在master节点上
        server: master 
      # nfs服务的目录
        path: /nfsdata


