apiVersion: v1
kind: Service
metadata:
  name: mysql57
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  type: NodePort
  ports:
  # service对外暴露的端口
  - port: 3306
  # Pod本身暴露的端口，即service会将来自3306端口的请求转发给底层容器所暴露的3306端口
    targetPort: 3306
    # 将来自宿主机的30306的流量转发到service的3306端口，然后service再转发给pod
    nodePort: 30306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
    # 对哪个pod做stateful，必须和.spec.template.metadata.labels一样
      app: mysql
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: registry.cn-beijing.aliyuncs.com/qingfeng666/mysql:5.7
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: host-path
          mountPath: /var/lib/mysql
        env: 
          - name: MYSQL_ROOT_PASSWORD
            value: "password"
      volumes: 
        - name: host-path
          hostPath:
            path: /tmp/mysql
            type: DirectoryOrCreate
