apiVersion: v1
kind: Pod
metadata:
  name: pod-test
spec:
  containers:
  - name: myapp
    image: busybox
    # 展示环境变量
    command: ["/bin/sh", "-ce", "sleep 36000"]
    # 指定环境变量从哪里来
    envFrom:
      - configMapRef:
          name: appvar
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
